### PR TITLE
Feature/admin - Admin Api - Admin Frontend Page Template setup

### PR DESCRIPTION
**Pull request by aa1588**
### Purpose
This pull request implements a few adim apis and sets up frontend admin page template.

### Summary of changes
- Create Admin API for - Change User Account Status (ACTIVE,INACTIVE,FROZEN)
- GET User Stats for Admin Dashboard (total users/frozen accounts / active accounts/ total items, etc)
- GET backend (server) health endpoint

### Related Issues
- USER STORY - #7 
- TASK- #109

### CODE REVIEW

**Comment by aa1588** [comment]
image

**Comment by aa1588** [comment]
image
image

**Comment by aa1588** [comment]
image
image
image

**Comment by aa1588** [comment]
image

**Comment by aa1588** [comment]
image

**Comment by aa1588** [comment]
image

image

**Review by sudinjoshi — APPROVED** [review]

**Pull request merged**
